# -*- coding: utf-8 -*-
"""ETL&EDA_TIENDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fPPv9PoTJdKOeKYLsWyr7Ng6VSBdcoX
"""

import pandas as pd

file_path = '/content/Ejercicio tienda.xlsx'
df = pd.read_excel(file_path)

print('Data loaded successfully. Here are the first 5 rows:')
display(df.head())

# Remove summary rows based on the 'Producto' column
df_clean = df[~df['Producto'].str.contains('Total', na=False)].copy()

# Define the new column names
new_column_names = {
    'Producto': 'Producto',
    'inventario': 'Inventario Inicial',
    'costo': 'Costo Unitario',
    'venta': 'Precio Venta Unitario',
    'Inventario nuevo': 'Inventario Final'
}

# Rename the columns
df_clean = df_clean.rename(columns=new_column_names)

print('DataFrame after filtering and renaming columns:')
display(df_clean.head())

# Fill NaN values in 'Inventario Final' with 'Inventario Inicial' values
df_clean['Inventario Final'] = df_clean['Inventario Final'].fillna(df_clean['Inventario Inicial'])

# Convert relevant columns to numeric types
# Using .astype(float) might introduce NaNs if there are non-numeric strings,
# so using pd.to_numeric with errors='coerce' is safer for robustness.
numeric_cols = ['Inventario Inicial', 'Costo Unitario', 'Precio Venta Unitario', 'Inventario Final']
for col in numeric_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

print('DataFrame after handling missing values and converting data types:')
display(df_clean.head())
print('\nData types after conversion:')
display(df_clean.info())

"""## Exploratory Data Analysis (EDA)

"""

print('Descriptive statistics for numerical columns:')
display(df_clean.describe())

print('\nMissing values per column after cleaning:')
display(df_clean.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

# Set the aesthetic style of the plots
sns.set_style('whitegrid')

# Create histograms for numerical columns
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Distribution of Key Numerical Features', fontsize=16)

sns.histplot(df_clean['Inventario Inicial'].dropna(), kde=True, ax=axes[0, 0], color='skyblue')
axes[0, 0].set_title('Distribution of Inventario Inicial')

sns.histplot(df_clean['Costo Unitario'].dropna(), kde=True, ax=axes[0, 1], color='lightcoral')
axes[0, 1].set_title('Distribution of Costo Unitario')

sns.histplot(df_clean['Precio Venta Unitario'].dropna(), kde=True, ax=axes[1, 0], color='lightgreen')
axes[1, 0].set_title('Distribution of Precio Venta Unitario')

sns.histplot(df_clean['Inventario Final'].dropna(), kde=True, ax=axes[1, 1], color='gold')
axes[1, 1].set_title('Distribution of Inventario Final')

plt.tight_layout(rect=[0, 0.03, 1, 0.96])
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Costo Unitario', y='Precio Venta Unitario', data=df_clean, hue='Producto', s=100)
plt.title('Costo Unitario vs. Precio Venta Unitario')
plt.xlabel('Costo Unitario')
plt.ylabel('Precio Venta Unitario')
plt.grid(True)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()