# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utHGNhsKzhQx-CzazmkyvdvVbCgM5H1E

## 1. Proceso ETL (Extract, Transform, Load)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar el dataset
df = pd.read_csv('/content/day.csv')

print("Primeras 5 filas del dataset:")
display(df.head())

print("\nInformación general del dataset (tipos de datos, valores no nulos):")
df.info()

print("\nEstadísticas descriptivas del dataset:")
display(df.describe())

df = df.rename(columns={
    'dteday': 'date',
    'yr': 'year',
    'mnth': 'month',
    'weathersit': 'weather_condition',
    'hum': 'humidity',
    'cnt': 'total_rentals',
    'casual': 'casual_rentals',
    'registered': 'registered_rentals'
})

print("Columnas después de renombrar:")
print(df.columns)

print("Valores faltantes por columna:")
display(df.isnull().sum())

# Convertir 'date' a tipo datetime
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

# Extraer características de la fecha
df['year'] = df['year'].map({0: 2011, 1: 2012})
df['month_name'] = df['date'].dt.month_name()
df['day_of_week'] = df['date'].dt.day_name()
df['weekday_num'] = df['date'].dt.weekday # Lunes=0, Domingo=6

# Mapear valores numéricos a etiquetas más descriptivas para las variables categóricas
df['season'] = df['season'].map({1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'})
df['weather_condition'] = df['weather_condition'].map({1: 'Clear/Few clouds', 2: 'Mist/Cloudy', 3: 'Light Rain/Snow', 4: 'Heavy Rain/Snow'})
df['holiday'] = df['holiday'].map({0: 'No Holiday', 1: 'Holiday'})
df['workingday'] = df['workingday'].map({0: 'Weekend/Holiday', 1: 'Working Day'})


print("Información del dataset después de conversiones y nuevas características:")
df.info()
print("\nPrimeras 5 filas con nuevas características:")
display(df.head())

"""## 2. EDA (Exploratory Data Analysis)"""

fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(18, 10))
fig.suptitle('Distribución de Variables Numéricas', fontsize=16)

sns.histplot(df['temp'], kde=True, ax=axes[0, 0], color='skyblue')
axes[0, 0].set_title('Temperatura (normalizada)')

sns.histplot(df['atemp'], kde=True, ax=axes[0, 1], color='lightcoral')
axes[0, 1].set_title('Sensación Térmica (normalizada)')

sns.histplot(df['humidity'], kde=True, ax=axes[0, 2], color='lightgreen')
axes[0, 2].set_title('Humedad (normalizada)')

sns.histplot(df['windspeed'], kde=True, ax=axes[1, 0], color='gold')
axes[1, 0].set_title('Velocidad del Viento (normalizada)')

sns.histplot(df['casual_rentals'], kde=True, ax=axes[1, 1], color='orange')
axes[1, 1].set_title('Alquileres Casuales')

sns.histplot(df['registered_rentals'], kde=True, ax=axes[1, 2], color='purple')
axes[1, 2].set_title('Alquileres Registrados')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['total_rentals'], kde=True, bins=30, color='teal')
plt.title('Distribución de Total de Alquileres de Bicicletas', fontsize=16)
plt.xlabel('Total de Alquileres')
plt.ylabel('Frecuencia')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(20, 12))
fig.suptitle('Distribución de Variables Categóricas', fontsize=16)

sns.countplot(x='season', data=df, ax=axes[0, 0], palette='viridis', order=['Spring', 'Summer', 'Fall', 'Winter'])
axes[0, 0].set_title('Temporada')

sns.countplot(x='year', data=df, ax=axes[0, 1], palette='plasma')
axes[0, 1].set_title('Año')

sns.countplot(x='month_name', data=df, ax=axes[0, 2], palette='mako')
axes[0, 2].set_title('Mes')
axes[0, 2].tick_params(axis='x', rotation=45)

sns.countplot(x='day_of_week', data=df, ax=axes[1, 0], palette='rocket', order=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
axes[1, 0].set_title('Día de la Semana')
axes[1, 0].tick_params(axis='x', rotation=45)

sns.countplot(x='holiday', data=df, ax=axes[1, 1], palette='crest')
axes[1, 1].set_title('Día Festivo')

sns.countplot(x='weather_condition', data=df, ax=axes[1, 2], palette='flare')
axes[1, 2].set_title('Condición Climática')
axes[1, 2].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

plt.figure(figsize=(15, 7))
sns.lineplot(x='date', y='total_rentals', data=df, color='blue', label='Total Rentals')
sns.lineplot(x='date', y='casual_rentals', data=df, color='green', label='Casual Rentals')
sns.lineplot(x='date', y='registered_rentals', data=df, color='red', label='Registered Rentals')
plt.title('Tendencia de Alquileres de Bicicletas a lo largo del tiempo', fontsize=16)
plt.xlabel('Fecha')
plt.ylabel('Número de Alquileres')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(18, 12))
fig.suptitle('Alquileres por Variables Categóricas', fontsize=16)

sns.boxplot(x='season', y='total_rentals', data=df, ax=axes[0, 0], palette='viridis', order=['Spring', 'Summer', 'Fall', 'Winter'])
axes[0, 0].set_title('Alquileres por Temporada')

sns.boxplot(x='month_name', y='total_rentals', data=df, ax=axes[0, 1], palette='mako')
axes[0, 1].set_title('Alquileres por Mes')
axes[0, 1].tick_params(axis='x', rotation=45)

sns.boxplot(x='day_of_week', y='total_rentals', data=df, ax=axes[1, 0], palette='rocket', order=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
axes[1, 0].set_title('Alquileres por Día de la Semana')
axes[1, 0].tick_params(axis='x', rotation=45)

sns.boxplot(x='weather_condition', y='total_rentals', data=df, ax=axes[1, 1], palette='flare')
axes[1, 1].set_title('Alquileres por Condición Climática')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

numerical_cols = ['temp', 'atemp', 'humidity', 'windspeed', 'casual_rentals', 'registered_rentals', 'total_rentals']
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Matriz de Correlación de Variables Numéricas', fontsize=16)
plt.show()

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(20, 6))
fig.suptitle('Relación del Clima con los Alquileres Totales', fontsize=16)

sns.scatterplot(x='temp', y='total_rentals', data=df, hue='weather_condition', size='humidity', sizes=(20, 400), ax=axes[0], palette='viridis')
axes[0].set_title('Temperatura vs. Total de Alquileres')

sns.scatterplot(x='humidity', y='total_rentals', data=df, hue='weather_condition', size='temp', sizes=(20, 400), ax=axes[1], palette='viridis')
axes[1].set_title('Humedad vs. Total de Alquileres')

sns.scatterplot(x='windspeed', y='total_rentals', data=df, hue='weather_condition', size='temp', sizes=(20, 400), ax=axes[2], palette='viridis')
axes[2].set_title('Velocidad del Viento vs. Total de Alquileres')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()