# -*- coding: utf-8 -*-
"""Momento_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsUzwiNjn9scIPr3xc1Ku3IdGpT4Tl-8
"""

df = pd.read_csv('/content/M2_viajes_agosto.csv')

import pandas as pd

# Estandarizar nombre de la estacion
df['estacion_origen'] = df['estacion_origen'].str.title()
df['estacion_destino'] = df['estacion_destino'].str.title()

# Convert date columns to datetime, coercing errors to NaT
df['fecha_inicio'] = pd.to_datetime(df['fecha_inicio'], errors='coerce', dayfirst=False)
df['fecha_fin'] = pd.to_datetime(df['fecha_fin'], errors='coerce', dayfirst=False)

display(df.head())

display(df.info())

"""### Manejo de Valores Faltantes y Conversión de Tipos de Datos

El paso anterior nos mostró que hay valores faltantes en varias columnas y que `costo` y `edad_usuario` siguen siendo de tipo 'object'. Procederemos a:

1. **Identificar valores faltantes:** Contar los valores `NaN` por columna.
2. **Limpiar y convertir `costo`:** Convertir a tipo numérico y corregir valores negativos o inconsistentes.
3. **Limpiar y convertir `edad_usuario`:** Convertir a tipo numérico y tratar posibles errores.
"""

print('Valores faltantes por columna:')
display(df.isnull().sum())

# Convertir "costo" a numérico.
# Asumiremos que los valores "object" son strings de números y los convertiremos a float.
df["costo"] = pd.to_numeric(df["costo"], errors="coerce")

# Corregir costos negativos: asumiendo que un costo negativo es un error y debería ser positivo.
df["costo"] = df["costo"].abs()

# Convertir 'edad_usuario' a numérico.
df['edad_usuario'] = pd.to_numeric(df['edad_usuario'], errors='coerce')

display(df.head())
display(df.info())

"""### Cálculo de Duración del Viaje

Ahora que `fecha_inicio` y `fecha_fin` son de tipo `datetime`, podemos calcular la duración exacta de cada viaje en minutos.
"""

df['duracion_calculada_min'] = (df['fecha_fin'] - df['fecha_inicio']).dt.total_seconds() / 60

display(df.head())
display(df.info())

